### ISSUE TITLE
Help to add me as a contributor to Diamond TEPs

### ISSUE THREAD

**Issue by Waztom** [asapdiscovery/asapdiscovery.github.io#84]
Hi @jchodera or @JenkeScheen - could you please direct me to the file I need to edit to add myself as a Diamond team contributor to ASAP TEPs?

**Comment by jchodera** [comment]
Apologies for the omission! We'll get this fixed!

The data for all the TEPs is here:
https://github.com/asapdiscovery/asapdiscovery.github.io/tree/main/data/outputs/TEPs
For now, could you just give me a list of TEPs to add you to?

I'm hoping we can eventually switch from attaching contributors to TEPs to attaching contributors to individual outputs/resources (e.g. protein construct plasmids, assay protocols, crystallization protocols, structures, group depositions, and fragment screens), but we'll need some folks to help annotate who did what at that level. Maybe we could schedule a separate time to talk through that step?

**Comment by Waztom** [comment]
No worries and thank you @jchodera! Please see list below.

Could you please add me to:
1. SARS-CoV-2 / MERS-CoV Mpro
2. Enterovirus D68 3C protease
3. Zika NS2B-NS3 protease
6. SARS-CoV-2 Mpro

Good idea annotating and aggregating by contribution. Happy to discuss and help get the annotations flowing from our end.

**Comment by jchodera** [comment]
Looks like these are fixed now!
